name: Spring Boot Build and Docker Image Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
           java-version: '17'
           distribution: 'adopt'

      - name: Build Spring Boot application
        run: mvn clean install -DskipTests
        working-directory: ./Backend/closebacked

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: Backend/closebacked/
          push: false
          tag: ykanjiya/springapp:v2
          
      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: Backend/closebacked/
          push: true  
          tags: ykanjiya/springapp:v2 


  deploy: 
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image for docker hub
        run: docker pull ykanjiya/springapp:v2 
      - name: Delete old container if exists
        run: docker rm -f springContainer || true
      - name: Run docker container
      run: docker run -d -p 9292:9292 --name springContainer ykanjiya/springapp:v2 